
name: 'Global_E_Commerce_Performance_Analysis'
version: '1.0.0'
profile: 'Global_E_Commerce_Performance_Analysis'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:        
  - "target"
  - "dbt_packages"
models:
  Global_E_Commerce_Performance_Analysis:
    example:
      +materialized: view
